//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// FILE NÀY KHÔNG SỬ DỤNG - Project đang dùng ADO.NET trong SinhVienService.cs
// Nếu bạn muốn dùng Entity Framework, hãy regenerate EDMX từ database QuanLySinhVienDB

/*
namespace Quanlysinhvien
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<hanghoa> hanghoas { get; set; }
        public DbSet<oto> otoes { get; set; }
        public DbSet<MSreplication_options> MSreplication_options { get; set; }
        public DbSet<spt_fallback_db> spt_fallback_db { get; set; }
        public DbSet<spt_fallback_dev> spt_fallback_dev { get; set; }
        public DbSet<spt_fallback_usg> spt_fallback_usg { get; set; }
        public DbSet<spt_monitor> spt_monitor { get; set; }
        public DbSet<spt_values> spt_values { get; set; }
    }
}
*/
